version: '3'

services:
  registry:
    image: registry:latest
    ports:
    - "5000:5000"
    restart:  always
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /mnt/nfs/:/data